version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: fifthkeys-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fifthkeys-network

  # Backend service
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: fifthkeys-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/fifthkeys
    depends_on:
      - mongodb
    networks:
      - fifthkeys-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fifthkeys-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fifthkeys-network

# Define a network
networks:
  fifthkeys-network:
    driver: bridge

# Define volumes
volumes:
  mongodb_data:
    driver: local 